### ISSUE TITLE
Interface design

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/mustard#3]
Design the interface (any prototype would be enough for us to discuss)

**Comment by angrykoala** [comment]
For now, vue.js seems to be the preferred options for the front-end framework

**Comment by angrykoala** [comment]
@mpvillafranca , @MarFerPra who wants to start with this? assign please

**Comment by angrykoala** [comment]
We should also decide on a css framework (if any). Please, not bootstrap

**Comment by marco-fp** [comment]
I'd say Materialize, since all the cool kids are using it.

**Comment by angrykoala** [comment]
Materialize is not very good when it comes to forms. We would need to use a different one for those (or a different one for everything) as we need good nice forms and tables for our tags

PS: Gaucho uses Materialize, you can check it there

**Comment by mpvillafranca** [comment]
I found this two CSS frameworks:

- http://foundation.zurb.com/
- http://semantic-ui.com/

I like how the second one looks!

**Comment by angrykoala** [comment]
I don't like zurb, but the semantic one seems to have a lot of fancy inputs and components so it may be useful.

We could make a small test integrating it with electron (in a separate branch)

**Comment by angrykoala** [comment]
To integrate semantic-ui we could either use the npm package <https://www.npmjs.com/package/semantic-ui> or the minified version

We should try with the package first

**Comment by marco-fp** [comment]
@angrykoala What issues did you have with Materialized forms? I'm curious.

**Comment by angrykoala** [comment]
It's quite hard to modify them, and basically there is only one type of input type which doesn't even look nice when added to a form with other inputs. While materialize is nice for clean menus, buttons etc..., we need a framework more form-oriented, as mustard will be forms and tables basically @MarFerPra

**Comment by mpvillafranca** [comment]
Why did you upload the semantic-ui as a resource in the repo? Maybe we can just use the npm package, so we don't need to include third party stuff here...

**Comment by angrykoala** [comment]
@mpvillafranca check #4 
Adding it as a dependency requires (or at least, seems to require) a build step with browserify or webpack. I agree with that, but I don't want to have a build process so early (or, to be honest, I'm too lazy to do it atm) feel free to change the way it is loaded (that would be part of #4)
